name: Bandit

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
